# Generated by Django 2.0.6 on 2018-06-08 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CDO', '0002_auto_20180608_1827'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('org_id', models.AutoField(primary_key=True, serialize=False)),
                ('org_name', models.CharField(max_length=100)),
                ('org_date', models.CharField(blank=True, max_length=100, null=True)),
                ('org_location', models.CharField(blank=True, max_length=100, null=True)),
                ('org_about', models.CharField(default='', max_length=1000)),
                ('org_dir_name', models.CharField(blank=True, max_length=100, null=True)),
                ('org_dir_surname', models.CharField(blank=True, max_length=100, null=True)),
                ('org_dir_birth', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'managed': True,
            },
        ),
    ]
